AWSTemplateFormatVersion: "2010-09-09"
Description: >
  frontend subsystem - フロントエンドSPA配信用CloudFront（developのみ）

Parameters:
  ServiceName:
    Type: String
    Description: サービス名
  Stage:
    Type: String
    AllowedValues:
      - develop
      - release
    Description: デプロイステージ
  SecretReferer:
    Type: String
    NoEcho: true
    Description: シークレットトークン
  SubSystem:
    Type: String
    Default: frontend
    AllowedValues:
      - frontend
    Description: サブシステム分類名
  ApiGatewayDomain:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /develop/contactform-api-public/api/ApiGatewayDomain
    Description: "SSM Parameter Path for ApiGatewayDomain"
  FrontendWebsiteURL:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /develop/contactform-api-public/retained/FrontendWebsiteURL
    Description: "SSM Parameter Path for FrontendWebsiteURL"
  ReviewWebsiteURL:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /develop/contactform-api-public/retained/ReviewWebsiteURL
    Description: "SSM Parameter Path for ReviewWebsiteURL"

Conditions:
  IsRelease: !Equals [!Ref Stage, release]

Resources:
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    DeletionPolicy: !If [IsRelease, Retain, Delete]
    UpdateReplacePolicy: !If [IsRelease, Retain, Delete]
    Properties:
      DistributionConfig:
        Enabled: true
        HttpVersion: http2and3
        DefaultRootObject: index.html
        Origins:
          - Id: FrontendS3WebsiteOrigin
            DomainName: !Ref FrontendWebsiteURL
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
            OriginCustomHeaders:
              - HeaderName: "Referer"
                HeaderValue: !Ref SecretReferer
          - Id: ReviewS3WebsiteOrigin
            DomainName: !Ref ReviewWebsiteURL
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
            OriginCustomHeaders:
              - HeaderName: "Referer"
                HeaderValue: !Ref SecretReferer
          - Id: ApiGatewayOrigin
            DomainName: !Ref ApiGatewayDomain
            CustomOriginConfig:
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
        DefaultCacheBehavior:
          TargetOriginId: FrontendS3WebsiteOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          Compress: true
        CacheBehaviors:
          - PathPattern: /review/*
            TargetOriginId: ReviewS3WebsiteOrigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
            CachedMethods:
              - GET
              - HEAD
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
            Compress: true
          - PathPattern: /api/*
            TargetOriginId: ApiGatewayOrigin
            ViewerProtocolPolicy: redirect-to-https
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
            OriginRequestPolicyId: b689b0a8-53d0-40ab-baf2-68738e2966ac
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - PATCH
              - POST
              - DELETE
        PriceClass: PriceClass_200

  DomainNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${Stage}/${ServiceName}/${SubSystem}/DomainName"
      Type: String
      Value: !GetAtt CloudFrontDistribution.DomainName
      Description: "Frontend CloudFront DomainName"

  DistributionIDParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${Stage}/${ServiceName}/${SubSystem}/DistributionID"
      Type: String
      Value: !Ref CloudFrontDistribution
      Description: "Frontend CloudFront DistributionID"

Outputs:
  ServiceSubSystem:
    Description: Service and subsystem identifier
    Value: !Sub "${ServiceName}-${SubSystem}"
  CloudFrontDomainName:
    Description: CloudFront domain name for frontend
    Value: !GetAtt CloudFrontDistribution.DomainName
  FrontendCloudFrontDistributionId:
    Description: CloudFront distribution ID for frontend
    Value: !Ref CloudFrontDistribution
