//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

/// 問い合わせテーブルのSeaORMエンティティ
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "inquiries")]
pub struct Model {
    /// 問い合わせID (UUID v7)
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    /// 氏名
    #[sea_orm(column_type = "Text")]
    pub name: String,
    /// 連絡先メールアドレス
    #[sea_orm(column_type = "Text")]
    pub email: String,
    /// 作成日時
    pub created_at: DateTimeWithTimeZone,
    /// 問い合わせ本文
    #[sea_orm(column_type = "Text")]
    pub body: String,
    /// 行ログ (JSON形式で生リクエストを保存)
    #[sea_orm(column_type = "Text")]
    pub row_log: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
